#!/bin/bash
PASS=${PASS:-"docker"}
PORT=${PORT:-"5900"}

if [ $(echo -n $PASS | wc -c) -lt 6 ]; then
	echo -e "\x1B[01;33mVNC password is less than\x1B[0m \x1B[01;31m6 characters -\x1B[0m \x1B[01;33msetting to default\x1B[0m"
	PASS="docker"
fi

expect <<EOF
	spawn vncpasswd
	expect {
		-exact "Password" {send "$PASS\r"; exp_continue}
		-exact "Verify" {send "$PASS\r"; exp_continue}
		-exact "Would" {send "n\r"; exp_continue}
	}
EOF

vncserver -name LXDE -rfbport $PORT -depth 16 -geometry 1900x1200 -shmem -autokill -fg -localhost no
