---

- name: FPComplete | make sure dependencies are installed
  apt:
    pkg: "{{item}}"
    state: present
  with_items:  ["python-pycurl", "libncurses5-dev"]

- name: FPComplete | Add the FP Complete apt key
  apt_key: url=https://s3.amazonaws.com/download.fpcomplete.com/ubuntu/fpco.key state=present validate_certs=no
             
  
- name: FPComplete | Add the FP Complete repository
  apt_repository: repo="deb http://download.fpcomplete.com/ubuntu/{{ ansible_distribution_release }} stable main" state=present

- name: FPComplete | Install
  apt: name=stack state=present
  

