# Makefile autogenerated by Dyi on July 12, 2015
#
# Main target: all
# Sources: 

.DEFAULT_GOAL := all


.PHONY: prepare
prepare:




.PHONY: k-9fvweq5x
k-9fvweq5x:  
	git-hist history.md


.PHONY: k-225dg6g8
k-225dg6g8:  
	cat README.in.md history.md > README.md


.PHONY: k-bpu7hfqf
k-bpu7hfqf:  
	hub cm 'update history and readme'


.PHONY: all
all: 
	make k-9fvweq5x 
	make k-225dg6g8 
	make k-bpu7hfqf  


.PHONY: clean
clean:  


.PHONY: update
update: 
	make clean   
	node




