# Makefile autogenerated by Dyi on July 12, 2015
#
# Main target: all
# Sources: 

.DEFAULT_GOAL := all


.PHONY: prepare
prepare:




.PHONY: k-w60bx7hx
k-w60bx7hx:  
	git-hist history.md


.PHONY: k-ct9uts7a
k-ct9uts7a:  
	cat README.in.md history.md > README.md


.PHONY: all
all: 
	make k-w60bx7hx 
	make k-ct9uts7a  


.PHONY: clean
clean:  


.PHONY: update
update: 
	make clean   
	node




