# recall that you need a nerd font for neovim to function properly
font_family             JetBrainsMono Nerd Font
font_size               22.0
close_on_child_death    yes
macos_option_as_alt     yes
allow_remote_control    yes
enabled_layouts         tall,vertical,horizontal,fat,grid,stack
window_drag_tolerance   8
editor                  /opt/homebrew/bin/nvim
cursor_shape            block
# url_color #0087bd
url_style curly
url_prefixes file ftp ftps gemini git gopher http https irc ircs kitty mailto news sftp ssh message
map shift+enter         send_text all \x1bOM
map ctrl+shift+enter    launch --cwd=current
map ctrl+shift+1        edit_config_file
map ctrl+shift+2        load_config_file
map cmd+shift+left      previous_window
map cmd+shift+right     next_window
# map alt+shift+down      move_window down
# map alt+shift+up        move_window up
# map alt+shift+left      move_window left
# map alt+shift+right     move_window right

# tmux-style pane navigation
# map alt+left            neighboring_window left
# map alt+right           neighboring_window right
# map alt+up              neighboring_window up
# map alt+down            neighboring_window down
# 
# # tmux-style split
# map alt+v               launch --location=vsplit --cwd=current
# map alt+b               launch --location=hsplit --cwd=current
# 
# # tmux-style new window
# map alt+n               launch --type=window --cwd=current
# 
# # tmux-style tabs
# map ctrl+a>c            new_tab_with_cwd
# map ctrl+a>n            next_tab
# map ctrl+alt+left       previous_tab
# map ctrl+alt+right      next_tab



# mouse_map left            click ungrabbed mouse_click_url_or_select
# mouse_map shift+left      click grabbed,ungrabbed mouse_click_url_or_select
copy_on_select yes


include /Users/zaccaria/dotfiles/kitty-themes-master/themes/Brogrammer.conf

